[package]
name = "rls_to_syrust"
version = "0.1.0"
authors = ["Yoshiki Takashima <ytakashi@andrew.cmu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rls-analysis = "0.18.1"
log = "0.4"
